spring.application.name=backend

# 🐘 CONFIGURACIÓN DE POSTGRESQL (El motor de verdad)
spring.datasource.url=jdbc:postgresql://localhost:5432/sgtp_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driverClassName=org.postgresql.Driver

# 🛠️ HIBERNATE (JPA) - Constructor de Tablas Automático
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Opcional: Muestra en la consola de IntelliJ las consultas SQL que hace Java
spring.jpa.show-sql=false